system:
  http_port: "8080"
  base_path: "/"
  min_threads: 10
  max_threads: 100
  timeout: 10000
  address: "localhost"

database:
  jdbc_url: "jdbc:h2:mem:devDb;MODE=PostgreSQL;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS minesweeper_api"
  username: "user"
  password: "secret"
  driver_class_name: "org.h2.Driver"
  minimum_idle: "5"
  maximum_pool_size: "10"
  connection_timeout: "3000"
  idle_timeout: "6000"
  autocommit: true